sensor:
  - platform: adc
    pin: GPIO36
    id: temp_bedroom
    name: "Bedroom Temperature"
    update_interval: 1s
  - platform: adc
    pin: GPIO39
    id: temp_livingroom
    name: "Living Room Temperature"
    update_interval: 1s
  - platform: adc
    pin: GPIO34
    id: temp_mainhall
    name: "Main Hall Temperature"
    update_interval: 1s
