  # https://esphome.io/components/climate/thermostat.html
# climate:
#   - platform: thermostat
#     name: "Thermostat"
#     sensor: my_temperature_sensor
#     min_cooling_off_time: 300s
#     min_cooling_run_time: 300s
#     min_heating_off_time: 300s
#     min_heating_run_time: 300s
#     min_idle_time: 3s
#     cool_action:
#       # - switch.turn_on: air_cond
#       - fan.turn_on: fan_1
#       - fan.turn_on: fan_2
#     heat_action:
#       - switch.turn_on: heater
#     idle_action:
#       - switch.turn_off: air_cond
#       - switch.turn_off: heater
#     default_preset: Home
#     preset:
#       - name: Home
#         default_target_temperature_low: 20 °C
#         default_target_temperature_high: 22 °C
